#region Assembly Assembly-CSharp.dll, v2.0.50727
// C:\greg\games\KSP 0.18.2\KSP_Data\Managed\Assembly-CSharp.dll
#endregion

using System;
using UnityEngine;

/// <summary>
/// Contains some functions you can call to save the game state to a persistence file, or load the game state from a persistence file.
/// </summary>
public class GamePersistence : MonoBehaviour
{
    public extern GamePersistence();

    public extern static FlightState LoadFlightState(string filename, string saveFolder, bool haltIfIncompatible, bool suppressErrorMessage);
    public extern static Game LoadGame(string filename, string saveFolder, bool haltIfIncompatible, bool suppressErrorMessage);
    public extern static string SaveFlightState(string saveFileName, string saveFolder, SaveMode saveMode);
    public extern static string SaveFlightState(FlightState st, string saveFileName, string saveFolder, SaveMode saveMode);
    /// <summary>
    /// Creates a persistence file containing the current game state. Probably persistent.sfs and quicksave.sfs are
    /// generated by calls to this function.
    /// </summary>
    /// <param name="saveFileName">The name of the persistence file to create (".sfs" will be appended to the file name).</param>
    /// <param name="saveFolder">The folder in which to create the save file. Try using HighLogic.SaveFolder.</param>
    /// <param name="saveMode">Whether to overwrite, append, or abort if the given file already exists.</param>
    /// <returns>Returns the filename on success. Returns an empty string when the file already exists and SaveMode.ABORT is used.</returns>
    public extern static string SaveGame(string saveFileName, string saveFolder, SaveMode saveMode);
    public extern static string SaveGame(Game game, string saveFileName, string saveFolder, SaveMode saveMode);
}
